In [13]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

In [40]:
df = pd.read_pickle('../../output/data/final/original_extended_final.pkl')
df = df[df['AGE'].le(47) & df['SURVEY_YEAR'].ge(1979)]

In [41]:
df['CENSORED_NEXT_PERIOD'] = 0
last_year = df.groupby('IDENTIFIER').last().SURVEY_YEAR
cond = list(zip(last_year.index, last_year))
df.loc[(cond), 'CENSORED_NEXT_PERIOD'] = 1
df['CENSORED_NEXT_PERIOD'] = df['CENSORED_NEXT_PERIOD'].astype(int)
df['SURVEY_YEAR'] = df['SURVEY_YEAR'].astype(int)

In [44]:
late_df = df[df['AGE'].le(46) & df['SURVEY_YEAR'].lt(2011) & df['SURVEY_YEAR'].gt(1994) & (df['SURVEY_YEAR'] % 2).eq(1)]

In [47]:
school_age_brackets = [[16, 17], list(range(18, 21))]

work_age_brackets = [list(range(18, 21)), list(range(21, 26)), 
                       list(range(26, 31)), list(range(31, 36)), list(range(36, 41)), list(range(41, 48))]

In [48]:

for bracket in work_age_brackets:
    
    df['employment_' + str(bracket[0]) + '_' + str(bracket[-1])] = (df['CHOICE'].isin(['blue_collar', 'white_collar', 'military']) 
                                                                                  & df['AGE'].isin(bracket)).astype(int)
        
    
    for choice in ['blue_collar', 'white_collar', 'military']:
        
        df[choice + '_' + str(bracket[0]) + '_' + str(bracket[-1])] = (df['CHOICE'].eq(choice) 
                                                                       & df['AGE'].isin(bracket)).astype(int)

In [49]:
for bracket in school_age_brackets:
    
    df['school_' + str(bracket[0]) + '_' + str(bracket[-1])] = (df['CHOICE'].eq('schooling') 
                                                                & df['AGE'].isin(bracket)).astype(int)

In [50]:
formula = 'CENSORED_NEXT_PERIOD ~ employment_31_35 + employment_36_40 + employment_41_47 + C(AGE) + C(SURVEY_YEAR)'

mod = smf.probit(formula, df)
res = mod.fit()
print(res.summary())

Optimization terminated successfully.
         Current function value: 0.140737
         Iterations 7
                           Probit Regression Results
================================================================================
Dep. Variable:     CENSORED_NEXT_PERIOD   No. Observations:                 8319
Model:                           Probit   Df Residuals:                     8292
Method:                             MLE   Df Model:                           26
Date:                  Tue, 09 Jun 2020   Pseudo R-squ.:                 0.02536
Time:                          16:40:50   Log-Likelihood:                -1170.8
converged:                         True   LL-Null:                       -1201.3
Covariance Type:              nonrobust   LLR p-value:                 0.0001252
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -1.8486      0.439     -4.209      0.000      -2.709      -0.988
C(AGE)[T.31.0]            -0.4031      0.503     -0.801      0.423      -1.390       0.583
C(AGE)[T.32.0]            -0.4927      0.505     -0.976      0.329      -1.482       0.497
C(AGE)[T.33.0]            -0.3290      0.491     -0.670      0.503      -1.291       0.633
C(AGE)[T.34.0]            -0.4878      0.497     -0.981      0.326      -1.462       0.486
C(AGE)[T.35.0]            -0.2449      0.509     -0.481      0.631      -1.243       0.753
C(AGE)[T.36.0]             0.0983      0.491      0.200      0.841      -0.864       1.061
C(AGE)[T.37.0]             0.0955      0.509      0.188      0.851      -0.902       1.093
C(AGE)[T.38.0]            -0.1453      0.515     -0.282      0.778      -1.155       0.864
C(AGE)[T.39.0]            -0.1319      0.526     -0.251      0.802      -1.163       0.899
C(AGE)[T.40.0]            -0.2662      0.530     -0.502      0.615      -1.304       0.772
C(AGE)[T.41.0]            -0.2976      0.542     -0.549      0.583      -1.360       0.764
C(AGE)[T.42.0]            -0.4789      0.547     -0.876      0.381      -1.551       0.593
C(AGE)[T.43.0]            -0.7819      0.571     -1.370      0.171      -1.901       0.337
C(AGE)[T.44.0]            -0.5280      0.566     -0.932      0.351      -1.638       0.582
C(AGE)[T.45.0]            -0.8561      0.581     -1.474      0.140      -1.994       0.282
C(AGE)[T.46.0]            -0.6690      0.578     -1.156      0.248      -1.803       0.465
C(SURVEY_YEAR)[T.1997]     0.2112      0.156      1.354      0.176      -0.094       0.517
C(SURVEY_YEAR)[T.1999]     0.0534      0.206      0.260      0.795      -0.350       0.456
C(SURVEY_YEAR)[T.2001]     0.3863      0.245      1.580      0.114      -0.093       0.866
C(SURVEY_YEAR)[T.2003]     0.4715      0.279      1.690      0.091      -0.075       1.018
C(SURVEY_YEAR)[T.2005]     0.4664      0.315      1.478      0.139      -0.152       1.085
C(SURVEY_YEAR)[T.2007]     0.9964      0.350      2.845      0.004       0.310       1.683
C(SURVEY_YEAR)[T.2009]     1.1667      0.371      3.144      0.002       0.439       1.894
employment_31_35           0.1435      0.190      0.754      0.451      -0.229       0.516
employment_36_40          -0.2299      0.117     -1.971      0.049      -0.458      -0.001
employment_41_47          -0.1738      0.106     -1.636      0.102      -0.382       0.034
==========================================================================================

In [22]:
df[df['IDENTIFIER'].eq(7)]

                        IDENTIFIER  SURVEY_YEAR  RACE  SAMPLE_ID  GENDER  \
Identifier Survey Year
7          1980                  7         1980   3.0        1.0     1.0
           1981                  7         1981   3.0        1.0     1.0
           1982                  7         1982   3.0        1.0     1.0
           1983                  7         1983   3.0        1.0     1.0
           1984                  7         1984   3.0        1.0     1.0
           1985                  7         1985   3.0        1.0     1.0
           1986                  7         1986   3.0        1.0     1.0
           1987                  7         1987   3.0        1.0     1.0
           1988                  7         1988   3.0        1.0     1.0
           1989                  7         1989   3.0        1.0     1.0
           1990                  7         1990   3.0        1.0     1.0
           1991                  7         1991   3.0        1.0     1.0
           1992                  7         1992   3.0        1.0     1.0
           1993                  7         1993   3.0        1.0     1.0
           1994                  7         1994   3.0        1.0     1.0
           1995                  7         1995   3.0        1.0     1.0
           1996                  7         1996   3.0        1.0     1.0
           1997                  7         1997   3.0        1.0     1.0
           1998                  7         1998   3.0        1.0     1.0
           1999                  7         1999   3.0        1.0     1.0
           2000                  7         2000   3.0        1.0     1.0
           2001                  7         2001   3.0        1.0     1.0
           2002                  7         2002   3.0        1.0     1.0
           2003                  7         2003   3.0        1.0     1.0
           2004                  7         2004   3.0        1.0     1.0
           2005                  7         2005   3.0        1.0     1.0
           2006                  7         2006   3.0        1.0     1.0
           2007                  7         2007   3.0        1.0     1.0
           2008                  7         2008   3.0        1.0     1.0
           2009                  7         2009   3.0        1.0     1.0

                        ASVAB_ARITHMETIC_REASONING  ASVAB_WORD_KNOWLEDGE  \
Identifier Survey Year
7          1980                               14.0                  27.0
           1981                               14.0                  27.0
           1982                               14.0                  27.0
           1983                               14.0                  27.0
           1984                               14.0                  27.0
           1985                               14.0                  27.0
           1986                               14.0                  27.0
           1987                               14.0                  27.0
           1988                               14.0                  27.0
           1989                               14.0                  27.0
           1990                               14.0                  27.0
           1991                               14.0                  27.0
           1992                               14.0                  27.0
           1993                               14.0                  27.0
           1994                               14.0                  27.0
           1995                               14.0                  27.0
           1996                               14.0                  27.0
           1997                               14.0                  27.0
           1998                               14.0                  27.0
           1999                               14.0                  27.0
           2000                               14.0                  27.0
           2001                               14.0                  27.0
           2002                               14.0                  27.0
           2003                               14.0                  27.0
           2004                               14.0                  27.0
           2005                               14.0                  27.0
           2006                               14.0                  27.0
           2007                               14.0                  27.0
           2008                               14.0                  27.0
           2009                               14.0                  27.0

                        ASVAB_PARAGRAPH_COMPREHENSION  \
Identifier Survey Year
7          1980                                   8.0
           1981                                   8.0
           1982                                   8.0
           1983                                   8.0
           1984                                   8.0
           1985                                   8.0
           1986                                   8.0
           1987                                   8.0
           1988                                   8.0
           1989                                   8.0
           1990                                   8.0
           1991                                   8.0
           1992                                   8.0
           1993                                   8.0
           1994                                   8.0
           1995                                   8.0
           1996                                   8.0
           1997                                   8.0
           1998                                   8.0
           1999                                   8.0
           2000                                   8.0
           2001                                   8.0
           2002                                   8.0
           2003                                   8.0
           2004                                   8.0
           2005                                   8.0
           2006                                   8.0
           2007                                   8.0
           2008                                   8.0
           2009                                   8.0

                        ASVAB_NUMERICAL_OPERATIONS  ASVAB_ALTERED_TESTING  \
Identifier Survey Year
7          1980                               32.0                   51.0
           1981                               32.0                   51.0
           1982                               32.0                   51.0
           1983                               32.0                   51.0
           1984                               32.0                   51.0
           1985                               32.0                   51.0
           1986                               32.0                   51.0
           1987                               32.0                   51.0
           1988                               32.0                   51.0
           1989                               32.0                   51.0
           1990                               32.0                   51.0
           1991                               32.0                   51.0
           1992                               32.0                   51.0
           1993                               32.0                   51.0
           1994                               32.0                   51.0
           1995                               32.0                   51.0
           1996                               32.0                   51.0
           1997                               32.0                   51.0
           1998                               32.0                   51.0
           1999                               32.0                   51.0
           2000                               32.0                   51.0
           2001                               32.0                   51.0
           2002                               32.0                   51.0
           2003                               32.0                   51.0
           2004                               32.0                   51.0
           2005                               32.0                   51.0
           2006                               32.0                   51.0
           2007                               32.0                   51.0
           2008                               32.0                   51.0
           2009                               32.0                   51.0

                        ...  employment_36_40  blue_collar_36_40  \
Identifier Survey Year  ...
7          1980         ...                 0                  0
           1981         ...                 0                  0
           1982         ...                 0                  0
           1983         ...                 0                  0
           1984         ...                 0                  0
           1985         ...                 0                  0
           1986         ...                 0                  0
           1987         ...                 0                  0
           1988         ...                 0                  0
           1989         ...                 0                  0
           1990         ...                 0                  0
           1991         ...                 0                  0
           1992         ...                 0                  0
           1993         ...                 0                  0
           1994         ...                 0                  0
           1995         ...                 0                  0
           1996         ...                 0                  0
           1997         ...                 0                  0
           1998         ...                 0                  0
           1999         ...                 0                  0
           2000         ...                 1                  0
           2001         ...                 1                  0
           2002         ...                 1                  0
           2003         ...                 1                  0
           2004         ...                 0                  0
           2005         ...                 0                  0
           2006         ...                 0                  0
           2007         ...                 0                  0
           2008         ...                 0                  0
           2009         ...                 0                  0

                        white_collar_36_40  military_36_40  employment_41_47  \
Identifier Survey Year
7          1980                          0               0                 0
           1981                          0               0                 0
           1982                          0               0                 0
           1983                          0               0                 0
           1984                          0               0                 0
           1985                          0               0                 0
           1986                          0               0                 0
           1987                          0               0                 0
           1988                          0               0                 0
           1989                          0               0                 0
           1990                          0               0                 0
           1991                          0               0                 0
           1992                          0               0                 0
           1993                          0               0                 0
           1994                          0               0                 0
           1995                          0               0                 0
           1996                          0               0                 0
           1997                          0               0                 0
           1998                          0               0                 0
           1999                          0               0                 0
           2000                          1               0                 0
           2001                          1               0                 0
           2002                          1               0                 0
           2003                          1               0                 0
           2004                          0               0                 0
           2005                          0               0                 0
           2006                          0               0                 1
           2007                          0               0                 0
           2008                          0               0                 0
           2009                          0               0                 0

                        blue_collar_41_47  white_collar_41_47  military_41_47  \
Identifier Survey Year
7          1980                         0                   0               0
           1981                         0                   0               0
           1982                         0                   0               0
           1983                         0                   0               0
           1984                         0                   0               0
           1985                         0                   0               0
           1986                         0                   0               0
           1987                         0                   0               0
           1988                         0                   0               0
           1989                         0                   0               0
           1990                         0                   0               0
           1991                         0                   0               0
           1992                         0                   0               0
           1993                         0                   0               0
           1994                         0                   0               0
           1995                         0                   0               0
           1996                         0                   0               0
           1997                         0                   0               0
           1998                         0                   0               0
           1999                         0                   0               0
           2000                         0                   0               0
           2001                         0                   0               0
           2002                         0                   0               0
           2003                         0                   0               0
           2004                         0                   0               0
           2005                         0                   0               0
           2006                         1                   0               0
           2007                         0                   0               0
           2008                         0                   0               0
           2009                         0                   0               0

                        school_16_17  school_18_20
Identifier Survey Year
7          1980                    1             0
           1981                    1             0
           1982                    0             0
           1983                    0             0
           1984                    0             0
           1985                    0             0
           1986                    0             0
           1987                    0             0
           1988                    0             0
           1989                    0             0
           1990                    0             0
           1991                    0             0
           1992                    0             0
           1993                    0             0
           1994                    0             0
           1995                    0             0
           1996                    0             0
           1997                    0             0
           1998                    0             0
           1999                    0             0
           2000                    0             0
           2001                    0             0
           2002                    0             0
           2003                    0             0
           2004                    0             0
           2005                    0             0
           2006                    0             0
           2007                    0             0
           2008                    0             0
           2009                    0             0

[30 rows x 350 columns]

In [45]:
df['CENSORED_NEXT_PERIOD'].groupby(df['SURVEY_YEAR']).sum()

SURVEY_YEAR
1995    20
1997    40
1999    30
2001    46
2003    37
2005    23
2007    47
2009    30
Name: CENSORED_NEXT_PERIOD, dtype: int32